### ISSUE TITLE
Test to ensure that METADATA REQUIRE is equal to the package REQUIRE.

### ISSUE THREAD

**Issue by ivarne** [JuliaLang/METADATA.jl#1012]
It is easy to get the REQUIRE file from
`https://raw.githubusercontent.com/{{pkg.url}}/{{SHA1-hash}}/REQUIRE` (if the package is hosted on github). It would be nice if we could make inconcistencies trigger a travis error.

See: https://groups.google.com/forum/#!topic/julia-dev/9T6SF3L9YUc

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
