### ISSUE TITLE
Access to JuliaCIBot

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaLang/METADATA.jl#10560]
That thing is super useful for seeing if anything downstream breaks via your changes. Is there any way that can be ran before the tagging process?

**Comment by aviks** [comment]
We're still working out the mechanics of how to expose it. We do want to do this in some form, but the details are not yet finalised. Happy to talk, and useful to see the interest.

**Comment by bblankrot** [comment]
Any update on this? I have a build that runs on travis/appveyor but failed on JuliaCIBot; having direct access would really help with debugging.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
