### ISSUE TITLE
Amazon*.jl

### ISSUE THREAD

**Issue by samoconnor** [JuliaLang/METADATA.jl#10674]
Hi @tkelman 

I have 102 new AWS interface packages: https://github.com/JuliaAWS

Seems like a good use-case for Pkg3 sub-packages (see https://github.com/JuliaLang/Juleps/issues/8#issuecomment-320414239,  https://github.com/JuliaLang/Juleps/issues/8#issuecomment-320802362).

The question is, in the meantime, should I `Pkg.register()` them all?

Background info: https://github.com/JuliaCloud/AWS.jl/commit/e2cb295f810dd1480647071593bc40829a093bf1#commitcomment-23534256

**Comment by aviks** [comment]
Couldn't these be separate modules in the same package? Do they absolutely need to be in the different packages?

**Comment by samoconnor** [comment]
Is it possible to precompile individual submodules in a package? I can't see how to do that.
I've tried the structure below, but when I do `using AWSSDK.ACM` the entire `AWSSDK` module gets pre-compiled and I end up with a 14MB `AWSSDK.ji` file. That's too big when I'm trying to keep deployment container image sizes to a minimum (e.g. on Lambda).

_AWSSDK.jl:_
```julia
module AWSSDK

include("ACM.jl")
include("APIGateway.jl")
...
include("XRay.jl")
end
```

_ACM.jl:_
```julia
__precompile__()

module ACM
...
end
```

**Comment by samoconnor** [comment]
I've pushed the monolithic `AWSSDK.jl` to here : https://github.com/JuliaCloud/AWSCore.jl
Perhaps, while we wait for Pkg3, a single package like this is the best compromise.
I guess users who have an issue with the `.ji` size (maybe only me?) are free to comment-out the `include("Service.jl")` lines they don't need to get a smaller build.

**Comment by tkelman** [comment]
And are these completely autogenerated with no post-generation manual touchups? If the generation process doesn't take too long to run, seems like people who want things piecemeal could also locally run the generation script themselves to get the same pieces of code?

**Comment by samoconnor** [comment]
Yes, they are purely auto-generated.
The generator automatically fetches the source JSON files from github and caches the locally.
It takes about 1min to generate everything (currently it builds both the monolithic package and all the Amazon*.jl packages, so it could be made faster).

One possible impediment to users locally running the generation reliably is this: https://github.com/samoconnor/AWSCore.jl/blob/master/src/HTML2MD.jl
It runs a local NodeJS server to convert HTML to markdown (Currently Documenter.jl does not accept HTML embedded in markdown).

**Comment by tkelman** [comment]
Guess you could maybe have an option for a no-docs build as one potential way to alleviate that concern?

**Comment by samoconnor** [comment]
Package registration PR for AWSSDK.jl: https://github.com/JuliaLang/METADATA.jl/pull/10816
