### ISSUE TITLE
Pkg.update() gives errors for older versions of Julia

### ISSUE THREAD

**Issue by TheOriginalSoni** [JuliaLang/METADATA.jl#10873]
I am currently running Julia Version 0.4.5 x86_64-linux-gnu.

When I run Pkg.update() on it, I get the following error - 
```

INFO: Initializing package repository /home/username/.julia/v0.4
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
fatal: unable to connect to github.com:
github.com[0: 192.30.253.112]: errno=Connection refused
github.com[1: 192.30.253.113]: errno=Connection refused

ERROR: failed process: Process(`git clone -q -b metadata-v2 git://github.com/JuliaLang/METADATA.jl METADATA`, ProcessExited(128)) [128]
 in anonymous at ./pkg/dir.jl:52
```

What is the fix to this error?

P.S. I got this version of Julia after running sudo apt-get install julia on Ubuntu (16.04)

**Comment by fredrikekre** [comment]
Not a direct fix to the problem, but you really shouldn't use such an old (and now unmaintained) release. You can download the latest 0.6.0 release here: https://julialang.org/downloads/

**Comment by TheOriginalSoni** [comment]
That I realised after a couple hours. But in that case, how does one go about changing what version of Julia one gets when they do `apt-get install julia`? That is how I installed Julia 0.4 on my system, and I believe a good number of people might use this way to test the language

**Comment by fredrikekre** [comment]
The recommended way to get julia is to download [generic binaries](https://julialang.org/downloads/) (or compile yourself). Using `apt-get` is not recommended, see https://github.com/JuliaLang/julialang.github.com/pull/475 for some more discussion.

**Comment by bjarthur** [comment]
perhaps not the same problem, but related possibly, is that package CI tests are failing on julia 0.5: 

```
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
 in macro expansion at ./libgit2/error.jl:99 [inlined]
 in clone(::String, ::String, ::Base.LibGit2.CloneOptions) at ./libgit2/repository.jl:191
 in #clone#112(::String, ::Bool, ::Ptr{Void}, ::Nullable{Base.LibGit2.AbstractCredentials}, ::Function, ::String, ::String) at ./libgit2/libgit2.jl:327
 in (::Base.LibGit2.#kw##clone)(::Array{Any,1}, ::Base.LibGit2.#clone, ::String, ::String) at ./<missing>:0
 in (::Base.Pkg.Dir.##4#6{String,String})() at ./pkg/dir.jl:49
 in cd(::Base.Pkg.Dir.##4#6{String,String}, ::String) at ./file.jl:59
 in init(::String, ::String) at ./pkg/dir.jl:47
 in #cd#1(::Array{Any,1}, ::Function, ::Function, ::String, ::Vararg{Any,N}) at ./pkg/dir.jl:28
 in clone(::String) at ./pkg/pkg.jl:151
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:242
 in _start() at ./client.jl:321
```

**Comment by andreasnoack** [comment]
@bjarthur See https://discourse.julialang.org/t/errors-for-git-pkg/9351
