### ISSUE TITLE
HEADS UP: datastructures upstreams using PQ will likely be broken

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/METADATA.jl#11065]
DataStructures 0.7 made a breaking change to `PriorityQueue`. Travis / JuliaCI didn't catch it, I guess. Anyway, I'm going to need some help setting upper bounds on earlier LightGraphs.jl versions. Paging @tkelman :)

**Comment by kmsquire** [comment]
I can make a quick release to special case the constructor that broke.

**Comment by sbromberger** [comment]
@kmsquire It won't be necessary for LightGraphs once #11066 gets merged and we UB previous versions, but I don't know which of the 500+ other upstreams need it :)

**Comment by kmsquire** [comment]
https://github.com/JuliaCollections/DataStructures.jl/pull/326
