### ISSUE TITLE
Add Pkg.status() output to JuliaCIBot

### ISSUE THREAD

**Issue by davidanthoff** [JuliaLang/METADATA.jl#11125]
It would be super useful if we knew exactly which versions of packages were used for a given JuliaCIBot run. Could we just add a ``Pkg.status()`` call somewhere in the JuliaCIBot script?

**Comment by ararslan** [comment]
cc @aviks

**Comment by aviks** [comment]
Yeah, will do.

**Comment by aviks** [comment]
This should be done now. It's visible at the end of the log.

**Comment by davidanthoff** [comment]
Great, thanks!
