### ISSUE TITLE
Registering a new package "Signals.jl"

### ISSUE THREAD

**Issue by TsurHerman** [JuliaLang/METADATA.jl#12215]
I want to register a new package , Signals.jl, I issued a pull request using attobot. 
This was 2 days ago, the PR says that it takes 24hrs till it is merged into METADATA .. 
Am I just being impatient or did I miss something in the registration process?

Thanks
Tsur

**Comment by aviks** [comment]
Just a backlog to get through

**Comment by TsurHerman** [comment]
Thought so , thanks!
