### ISSUE TITLE
UndefVarError: DynamicalODEProblem not defined

### ISSUE THREAD

**Issue by JoeMcEwen** [JuliaLang/METADATA.jl#12292]
@ChrisRackauckas 

I get the following error when trying to replicate the demo (https://julialang.org/blog/2017/11/gsoc-ode), 

UndefVarError: DynamicalODEProblem not defined

Additionally, information. 
Pkg.status("DiffEqBase")
returns : - DiffEqBase                    1.14.1

Pkg.status("DifferentialEquations") 
returns: - DifferentialEquations         2.2.1

Tried to update DifferentialEquations and got the following error. 
LoadError: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package  @DelayDiffEq.
  However, this only means that package DelayDiffEq is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.

I am running Julia version 0.06

**Comment by ChrisRackauckas** [comment]
I was trying to help @JoeMcEwen in a chatroom but I couldn't find anything that was keeping the packages so far back. I was wondering if there was a resolver error and if @carlobaldassi could help find out if that's the case.

**Comment by JoeMcEwen** [comment]
@ChrisRackauckas , @carlobaldassi 
Also, just tried removing DE package
Pkg.rm("DifferentialEquations")

got the following error: 
LoadError: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package ForwardDiff.
  However, this only means that package ForwardDiff is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.

**Comment by JoeMcEwen** [comment]
Update. I have now updated DifferentialEquations and DiffEqBase to current version. But, in the build process I get the following error

WARNING: Sundials, Rmath and RandomNumbers had build errors.

 - packages with build errors remain installed in /Users/joe/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("Sundials", "Rmath", "RandomNumbers")`
 - build a single package by running its `deps/build.jl` script

**Comment by ChrisRackauckas** [comment]
Those are just compilation issues. I assume you're on a Mac and haven't installed XCode or the XCode command line tool?

But okay, you updated. Does this mean it wasn't a resolver issue?

**Comment by JoeMcEwen** [comment]
I should have  Xcode installed. But, I did upgrade my OS the other day. That does usually cause problems. 

I can't say if it is a resolver issue. The issue persists. At a loss here.

**Comment by ChrisRackauckas** [comment]
You need not just XCode, but also the XCode command line tools to build the packages. But that's something we can work out in the chatroom.

How did you get the packages to update? Did you manually checkout master or latest releases?

**Comment by ChrisRackauckas** [comment]
It doesn't look like there's any actionable information on the resolver itself, which would be what this repo is for, so I am closing this. Feel free to ask any more questions in the other channels though!
