### ISSUE TITLE
Cap all former Datetime requires at julia 0.2- 0.4-

### ISSUE THREAD

**Issue by quinnj** [JuliaLang/METADATA.jl#1268]
Hey all,

I could use some help making sure the transition for Datetime.jl and Dates.jl is smooth heading into 0.4 with `Dates` now in Base. Here are a few thoughts/requirements, I guess I'm looking for feedback and what I need to do to make this happen:
* Ideally, Datetime.jl should only be used with 0.2
* The Dates.jl package will mirror Base (while maintaining 0.3 compatibility) and can be the package other packages depend on for 0.3 (I've started making PRs to packages currently depending on Datetime.jl). This is ideal because the syntax will be identical whether a package is using Dates.jl or Base (both can just use a `using Dates`), so hopefully the transition from 0.3 to 0.4 won't require any work

Anything else to think about?

**Comment by IainNZ** [comment]
At this point, meh.
