### ISSUE TITLE
Allow use to sort packages dynamically

### ISSUE THREAD

**Issue by goerz** [JuliaLang/METADATA.jl#13324]
It would be nice if the list of packages at http://pkg.julialang.org could be dynamically sorted. The alphabetic listing only seems moderately useful. One thing I'd be particularly interested in is sorting by popularity (Github stars). Also age (most recent update) might be a good sorting option.

To take this one step further, it might also be good to be able to filter the list, e.g. by supported Julia version, by license, or by whether tests are passing.

**Comment by andreasnoack** [comment]
This issue belongs at https://github.com/JuliaCI/PackageEvaluator.jl/issues where the website is residing. It would be great if you could submit as PR with the proposed improvements there as well.

**Comment by goerz** [comment]
Great, thanks.. I submitted it there at https://github.com/JuliaCI/PackageEvaluator.jl/issues/197

Unfortunately, I'm not really a frontend developer (i.e., I don't know JavaScript), so I'm not sure I'll be able to submit a PR. Still, I figured it would be ok as a feature request ;-)
