### ISSUE TITLE
Packages with resource address purged.

### ISSUE THREAD

**Issue by Nosferican** [JuliaLang/METADATA.jl#15100]
These packages no longer have their resources available.

Arduino: https://github.com/rennis250/Arduino.jl
ChainMap: https://github.com/bramtayl/ChainMap.jl
ControlCore: https://github.com/KTH-AC/ControlCore.jl
CorpusTools: https://github.com/mguzmann/CorpusTools
CreateMacrosFrom: https://github.com/bramtayl/CreateMacrosFrom.jl

**Comment by aviks** [comment]
cc: @rennis250 @bramtayl @KTH-AC @mguzmann 

We should update the entries, or deprecate the packages.

**Comment by Nosferican** [comment]
These packages would have to be depreciated. One way could be to completely purge them while an alternative would be to add them to a list which would throw an error à la
```
"The requested package is no longer available"
```
These are different from packages that redirect to a new address (see #15092).

**Comment by bramtayl** [comment]
I have several packages I'd like to depreciate if a mechanism exists...

**Comment by aviks** [comment]
To deprecate packages, set their max julia version to 0.7. By the time 1.0 comes around, they won't be installable.

**Comment by Nosferican** [comment]
These are all packages no longer installable since the repository has been deleted or made private.
```
["Arduino", "ChainRecursive", "Chunks", "CombinatorialBandits", "ControlCore",
  "DotOverloading", "DynamicalBilliardsPlotting", "GLUT", "GetC", "HTSLIB",
  "KeyedTables", "LazyCall", "LazyContext", "LazyQuery", "LibGit2", "NumberedLines",
  "OpenGL", "OrthogonalPolynomials", "Parts", "React", "RecurUnroll",
  "RequirementVersions", "SDL", "SessionHacker", "Sparrow", "StringArrays",
  "TypedBools", "ValuedTuples", "ZippedArrays"]
```
Should these be purged?

**Comment by Nosferican** [comment]
@StefanKarpinski What's the procedure here?

**Comment by StefanKarpinski** [comment]
For METADATA, we've just been leaving them. For the sync script that moves them to General, we have to blacklist them so the sync process doesn't break. I really wish that people wouldn't delete registered packages. We really need to build a system so that they're backed up even if someone deletes them.

**Comment by Nosferican** [comment]
Where exactly should I update the list for blacklisting these? I remember seeing a list in Pkg.jl, but these were identified directly from General.

**Comment by fredrikekre** [comment]
I don't think anything has to be done; packages that fail cloning are just skipped in the transfer process.

**Comment by Nosferican** [comment]
I have the functionality in DependenciesParser.jl to go from registry to the list of installable packages for statistics of the ecosystem so the registry could be left with those entries. Statistics on the ecosystem would just need to use the mapping from registry to installable packages to filter out uninstallable entries. For now, we could leave this caution and close the issue unless we decide something different for the future.

**Comment by omus** [comment]
Latest list of no longer installable packages:
```
["Arduino", "ChainMap", "ChainRecursive", "Chunks", "CombinatorialBandits",
"ContinuedFractions", "ControlCore", "CorpusTools", "CreateMacrosFrom", "DotOverloading",
"DynamicalBilliardsPlotting", "GLUT", "GSDicts", "GetC", "HTSLIB", "KeyedTables", "Keys",
"LazyCall", "LazyContext", "LazyQuery", "LibGit2", "NumberedLines", "OpenGL",
"OrthogonalPolynomials", "PackageGenerator", "Parts", "PhasedArrayTracking", "Processing",
 "React", "RecurUnroll", "RequirementVersions", "S3Dicts", "SDL", "SessionHacker",
 "SimilarReferences", "Sparrow", "TypedBools", "ValuedTuples", "ZippedArrays"]
```
The packages which were removed since the [last update](https://github.com/JuliaLang/METADATA.jl/issues/15100#issuecomment-461303233):
```
["ChainMap", "ContinuedFractions", "CorpusTools", "CreateMacrosFrom", "GSDicts", "Keys",
"PackageGenerator", "PhasedArrayTracking", "Processing", "S3Dicts", "SimilarReferences"]
```

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
