### ISSUE TITLE
Check that minimum Julia version is actually tested

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/METADATA.jl#17130]
An example happened yesterday when the minimum Julia version specified in REQUIRE was no longer being tested. It would be good to add a check for this.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
