### ISSUE TITLE
Set environment variable CI=true in JuliaCIBot?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/METADATA.jl#18630]
Is there a way for `test/runtests.jl` to tell if it is run inside JuliaCIBot?  I checked juliacibot.github.io (and https://github.com/JuliaCI/julia-buildbot though I guess it's not relevant) but I couldn't find information about it.

It would be nice `CI=true` is set _and_ documented that is set.  It seems this environment variable is set in many major CI platforms:

* https://docs.travis-ci.com/user/environment-variables/#convenience-variables
* https://www.appveyor.com/docs/environment-variables/
* https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables
* https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

This information is required for installing external packages such as Python packages before running tests:

* https://github.com/JuliaPy/PyCall.jl/blob/fb88f4d0df66fd2ce1bc4dc862611c355be0e50d/test/runtests.jl#L341
* https://github.com/JuliaPy/Conda.jl/blob/7094e2aad2aac5e21eb6db66ebab91c99bad3498/test/runtests.jl#L8
* https://github.com/tkf/IPython.jl/blob/91de79b3c05b7d8a31c2fe6cbb0f16944fc91f44/ci/before_script.jl#L28-L29

I think unconditionally installing external packages should be avoided since it would contaminate users' environment when they use `]test` or `include("test/runtests.jl")`.  That's why detecting JuliaCIBot is required.

**Comment by andreasnoack** [comment]
So indeed things could be better documented but `CI=true` is set on CIBot. Have you tested it?

**Comment by tkf** [comment]
Thanks! That's good to know. No, I haven't tested since, unlike Travis, testing JuliaCIBot will ping JuliaLang members and I didn't want to make noise.

**Comment by andreasnoack** [comment]
No problem. Good to know that it works.
