### ISSUE TITLE
Project.toml + REQUIRE?

### ISSUE THREAD

**Issue by phipsgabler** [JuliaLang/METADATA.jl#19416]
I have never published a package before, but for my recent work using Julia 1.0, I only used Pkg3-style dependencies with its `Project.toml` file.  However, there's no `REQUIRE` mentioned anywhere in the docs anymore since version 0.7, and `PkgDev` seems not to have been updated (as far as I understand).  

I also couldn't find any documentation about the interaction between `Pkg`, `PkgDev`, and `METADATA`  for current Julia at other places, so I'm not really sure about what I have to do to set up or "convert" a working package project in the sense of current `Pkg` into a form valid for publication in `METADATA`.  Do I just have to manually copy all dependencies from `Project.toml` into a `REQUIRE` file?

**Comment by andreasnoack** [comment]
We are currently in a transition phase which is the reason why things are not documented appropriately. However, please use Discourse for questions. This thread, https://discourse.julialang.org/t/the-current-metadata-release-process/16672, might answer some of your questions.
