### ISSUE TITLE
Case sensitivity package names

### ISSUE THREAD

**Issue by haampie** [JuliaLang/METADATA.jl#19739]
Moving the discussion from #19689 here:

Currently package names are case-sensitive which cause conflicts in the repo.

Apart from enforcing package names to be unique in a case-insensitive way, another suggestion in #19689 is to also enforce a minimal edit distance between package names (relative to the length I suppose).

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
