### ISSUE TITLE
Latest julia version is 0.7.0-DEV (unstable). Should be 1.x.x

### ISSUE THREAD

**Issue by houd1ni** [JuliaLang/METADATA.jl#19868]
https://pkg.julialang.org/

Please, add the real latest, stable, version. It affects the language popularity, 'cause it's the main registry, and, for example, badges: https://github.com/JuliaIO/JSON.jl/issues/271

**Comment by ararslan** [comment]
The pkg.julialang site is currently broken. This issue is unrelated to METADATA so I'm going to close it.
