### ISSUE TITLE
MAT.jl v0.4.0 should not be installable on Julia v1

### ISSUE THREAD

**Issue by jaakkor2** [JuliaLang/METADATA.jl#20430]
METADATA should not allow adding MAT.jl v0.4.0 on Julia v1.0.

If it is installed, `using MAT` results in an error, see https://github.com/JuliaIO/MAT.jl/issues/90 that was opened in August 2018.

**Comment by Nosferican** [comment]
Is any MAT.jl release supporting Julia `^1`?

**Comment by jaakkor2** [comment]
Last release of MAT.jl is v0.4.0 from Sept 15, 2017, so no, no release is supporting v1 at the moment.

**Comment by Nosferican** [comment]
Guess the preferred path would be to modify the compatibility specification.

**Comment by Nosferican** [comment]
Not sure how to fix the Compat in General without getting bit by the synch from METADATA, any guidance there?

Would changing the REQUIRE from
```
julia 0.5
```
to
```
julia 0.5 1
```
fix this with the next synch?

**Comment by jaakkor2** [comment]
MAT v0.5.0 has been tagged, solving this issue.
