### ISSUE TITLE
Accidental verson published

### ISSUE THREAD

**Issue by haydenfree** [JuliaLang/METADATA.jl#20515]
Hello,

I work on the CurricularAnalytics package and we accidentally pulled in version 2.2.5 instead of 0.2.5.
Is there any way to remove this version from METADATA? We don't want users to receive it as the "newest" version.

Thank you,
Hayden

**Comment by andreasnoack** [comment]
Sorry that this one wasn't noticed. You can revert the release here in METADATA. Try searching the old PRs for "revert". Let us know if it isn't clear how to proceed.

**Comment by haydenfree** [comment]
@andreasnoack 
> 
> 
> Sorry that this one wasn't noticed. You can revert the release here in METADATA. Try searching the old PRs for "revert". Let us know if it isn't clear how to proceed.

No problem. I am having a hard time seeing what I need to do. I looked it up but I don't see the button to revert on the pull request causing the issue. I apologize for the trouble, I've never had to do a revert before.

Thank you!

**Comment by haydenfree** [comment]
@andreasnoack Hi there. I'm so sorry to be a bother but I am looking to get this fixed as quick as possible. I would appreciate any help you can offer 😄

**Comment by andreasnoack** [comment]
You revert the commit at the command line. I've done it in https://github.com/JuliaLang/METADATA.jl/pull/20967. I'll merge once tests pass and then the release should be gone.
