### ISSUE TITLE
Existing package uuids incompatible with Pkg.METADATA_compatible_uuid

### ISSUE THREAD

**Issue by dillondaudert** [JuliaLang/METADATA.jl#20761]
The uuids returned by `METADATA_compatible_uuid` aren't equal to the uuids for existing packages, see:
[one](https://travis-ci.org/JuliaLang/METADATA.jl/jobs/482970483#L516), [two](https://travis-ci.org/JuliaLang/METADATA.jl/jobs/482923117#L516), [three](https://travis-ci.org/JuliaLang/METADATA.jl/jobs/482719630#L516)

Is it intended that all currently registered packages must update their uuids?

**Comment by fredrikekre** [comment]
> Is it intended that all currently registered packages must update their uuids?

Yes, if you manually added the wrong uuid you should update it.

**Comment by dillondaudert** [comment]
I'm guessing this is happening because the package was renamed after the uuid was generated.
