### ISSUE TITLE
Package test status not updating on http://pkg.julialang.org

### ISSUE THREAD

**Issue by KristofferC** [JuliaLang/METADATA.jl#2151]
I added my package (KDTrees) a week ago but I had forgotten to add the REQUIRE file to my test directory causing the automatic test to fail.

However, after that I have published new tagged versions that should fix this. However, my package is still stuck on the original version. On the site it says:

`Current version: 0.5.0 (6 days ago)`

Even though it is updated in METADATA.jl to a newer version. Do I have to manually tell package listing that my package is updated or something? I see that other packages has been updated on the site quite recently.

Best regards,
Kristoffer.

**Comment by KristofferC** [comment]
I looked around a bit and is it correct I have to add for example

`julia 0.3-`

to my REQUIRE file?

**Comment by IainNZ** [comment]
No you don't need that. I see you just added https://github.com/KristofferC/KDTrees.jl/commit/0b5723d74f91b2ac4537e60eaa4b3d4de604dbd5 `julia 0.2-`, which means you support Julia 0.2 prereleases, which I'm pretty sure you don't. You should check the manual about version numbers - you probably want `julia 0.3`.

Anyway, PkgEval runs only ever ~24 hours or so, but there was a bug in a package that it uses that prevented it from running for longer. I'm actually uploading results right now

**Comment by IainNZ** [comment]
Alas, that package is still broken it seems. I checked manually, and it looks like its passing now:

```json
{
  "jlver": "0.3",
  "name": "KDTrees",
  "url": "http://github.com/KristofferC/KDTrees.jl",
  "version": "0.5.2",
  "gitsha": "1ffbaf7095119329d5b869327b9f5c67febe7a30",
  "gitdate": "2015-02-13 00:03:48 +0100",
  "license": "MIT",
  "licfile": "LICENSE.md",
  "status": "full_pass",
}
```

**Comment by KristofferC** [comment]
Just informing that website still has not updated test status or version of KDTrees.jl.

**Comment by IainNZ** [comment]
The website is "broken", in the sense that there have been some issues with dependencies. I'll get to it when I can.
