### ISSUE TITLE
Should catch disagreement between Project.toml:[compat] and REQUIRE

### ISSUE THREAD

**Issue by timholy** [JuliaLang/METADATA.jl#22416]
#22412 allowed a mistake to slip through, see https://github.com/timholy/Revise.jl/issues/256. Ideally we should catch such problems automatically.

**Comment by tpapp** [comment]
Or, ideally, even ignore `REQUIRE` if `Project.toml` is available.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
