### ISSUE TITLE
Monotonically increasing version numbers? 

### ISSUE THREAD

**Issue by jakebolewski** [JuliaLang/METADATA.jl#2288]
Currently the tests do not check for this, so it is possible to mistag a package (ex. v"0.2.8" -> v"0.3.0" -> v"0.2.9" -> v"0.3.1")

**Comment by IainNZ** [comment]
Not sure if it can be done - there are some packages (or were some) that have two different series of releases. I expect there to be some of this when 0.4 comes out and people maintaining a separate line of releases for a while for 0.3. I'd agree though that this represents a small usage

**Comment by jakebolewski** [comment]
I didn't realize that people were doing this already, I think that is a good use case to support.
