### ISSUE TITLE
METADATA abandoned (?)

### ISSUE THREAD

**Issue by rapus95** [JuliaLang/METADATA.jl#22914]
should be marked abandoned & could be archived IIUC as pre 1.0 doesn't need to be supported (&thus no updates will be required)
Also update the readme and the description of the repo. Currently it still links to latest Pkg which is wrong

**Comment by fingolfin** [comment]
Also https://pkg.julialang.org/docs/ is stuck at showing outdated data with no hint that it is outdated. IMHO this looks really, really bad from the outside.

Possible options:

 1. change https://pkg.julialang.org/ to show data based on https://github.com/JuliaRegistries/General (best for users, but most work to implement, I assume?)

2. add a big bold banner to https://pkg.julialang.org stating that it is obsolete and outdated

3. Disable https://pkg.julialang.org (or change it to a redirect to something else).


Ping @KristofferC @ViralBShah (two people I saw had commits here and who might know who is in a position to handle this).

**Comment by aviks** [comment]
I've documented the abandonment of this repo. 

Separately, `pkg.julialang.org` will go away in a few days.
