### ISSUE TITLE
Remove FoundationDB

### ISSUE THREAD

**Issue by Keno** [JuliaLang/METADATA.jl#2346]
FoundationDB was [acquired by Apple](http://techcrunch.com/2015/03/24/apple-acquires-durable-database-company-foundationdb/) and has pulled all their repositories, including the Julia bindings. Unless somebody has a recent fork (and the license is ok), we should remove it from METADATA.

**Comment by tkelman** [comment]
According to pkg.julialang.org the Julia bindings were MIT-licensed, so if anyone has a clone you could push it to github, but that doesn't do much good without the corresponding core library, and I don't think that had a permissive license. Could we maybe get a comment from @wwilson?

**Comment by jiahao** [comment]
The repository for FoundationDB.jl has been deleted from GitHub.
