### ISSUE TITLE
Lots of recent timeouts

### ISSUE THREAD

**Issue by jiahao** [JuliaLang/METADATA.jl#2355]
Is there something we can do to increase the 10 minute timeout and/or make Pkg run faster?

**Comment by IainNZ** [comment]
I think its only 10 minutes of no output - can it just print something?

**Comment by jiahao** [comment]
`ProgressMeter.@showprogress`?

**Comment by tkelman** [comment]
Make it output something (even just a single character) at least once every 10 minutes and the timeout will be more generous, 50 mins or so. ProgressMeter should work if we know the total number of items we're looping through and each one takes reliably less than 10 minutes, which I think should be the case here. In other cases I've used some trivial little ruby wrapper script to just run something in the background and output a `.` every 10 seconds. I can't find that exact ruby wrapper at the moment, but shouldn't be too hard to recreate.

**Comment by jiahao** [comment]
Just about every PR in the past few days has timeout.

Maybe we should switch to testing on 0.4-dev, or backport the speedup.

**Comment by WestleyArgentum** [comment]
Maybe this is hacky, but we could also probably introduce some printing to the "Verifying Metadata" step. Maybe you'd be able to set a flag `verbose = true` and it would print the names of packages as it checked them...

**Comment by WestleyArgentum** [comment]
Guess that doesn't solve the testing on old versions problem though
