### ISSUE TITLE
Namespacing

### ISSUE THREAD

**Issue by IainNZ** [JuliaLang/METADATA.jl#2417]
Thoughts:
- METADATA is a single namespace
- This works for many other languages/platforms, including AFAIK Python, Ruby, and Node.js.
  - See https://github.com/npm/npm/issues/798 for pretty interesting discussion for NPM
  - Which mutated into this https://github.com/npm/npm/issues/5239 and https://docs.npmjs.com/misc/scope apparently
- There is something that we have that those systems don't - very strong name rules
- My theory is that relaxing name rules provide a pressure release valve
  - Can use "clever" names, e.g. for mutiple HTTP servers packages
    - We already allow this for things that more obviously need multiple packages, e.g. Convex+JuMP, or Mocha, or the higher-level web stack packages
  - Can do some manual namespacing, e.g. orgname_pkgname
    - That would be fairly un-Julian in appearance

Some options:
- Relax naming rules
- Leave METADATA as a highly curated repository, and create a new, looser registry

**Comment by tkelman** [comment]
Somewhat related, teaching Pkg how to declare dependencies on non-registered packages.

**Comment by IainNZ** [comment]
Indeed, and maybe even having simultanuous access to a private METADATA-like thing

**Comment by dcjones** [comment]
Related issue I made a while back: https://github.com/JuliaLang/julia/issues/5670

**Comment by dpsanders** [comment]
On a related note (and with the recent discussion about naming), the name "METADATA" itself does not follow the naming conventions, being too generic. As a possibly far out suggestion, how about renaming it to something like
- JuliaPackages
- RegisteredPackages
- PackageList
- _PackageList_

where the underscores replace the SHOUTING IN ALL CAPS and indicate its special nature.

As regards namespacing, the organisations sort of go some way to solving this (or could do).

**Comment by bicycle1885** [comment]
An idea:

* Create a new concept: meta package
* A meta package can hold packages and other meta packages.
* The current METADATA.jl is a meta package and we leave it as is.
* HDF5.jl, Gadfly.jl, etc. are packages.

UNIX filesystem analogy:
* file => package
* directory => meta package
* root directory => METADATA.jl

Advantages:
* Organizations can create their own meta package.
  * e.g. BioJulia organization may want to create a meta package named "Bio.jl"
* Maintainers of METADATA.jl can leave package management to each organization.
  * Distributed management will be simpler and scale.
* Nesting meta packages enables creating subgroups in an organization.

I'm sorry if I'm going off the topic.

**Comment by StefanKarpinski** [comment]
The point of METADATA.jl is to have a single central point where you can get all the data you need to resolve dependency computations. If it were federated, then it would no longer be central, defeating the purpose. The only way this might make sense is if you also layered the dependency structure so that metapackages can only depend on themselves or "top-level" packages. That seems like introducing an undesirable constraint on how packages can depend on each other. We could allow some leading directory structure in package names, which would have a similar effect without federating the metadata.

**Comment by wildart** [comment]
I think we should allow some namespace prefix for packages, and start to curate unprefixed one. In this way, we'll create set of selected packages in the existed METADATA structure and relax naming of new packages avoiding future name collisions.

**Comment by tkelman** [comment]
+1 to @wildart's suggestion. Some opt-in mechanism for adding namespaced package sources would probably be a good idea too, like conda channels or PPA's. That way if we're not enforcing any standards on namespaced packages, we would require an extra step for users to say they're willing to pull code that hasn't been vetted.

**Comment by tbreloff** [comment]
+1 to namespacing or labeling of some kind.   This could also allow the possibility of easily building "packages of packages".  For example, I would love if I could do `Pkg.add("JuliaStats")` and get all the best-of-breed packages as decided by the members of JuliaStats.  It can be hard work for a new user to _find_ all the packages they want, let alone figuring out how to use them.  (I know from personal experience)

**Comment by IainNZ** [comment]
Cleaning up. Pkg3 solves this.
