### ISSUE TITLE
Document earlier the process of tagging a version.

### ISSUE THREAD

**Issue by milktrader** [JuliaLang/METADATA.jl#2481]
It seems new developers get through the process of publishing their first package but miss the relevance of tagging a version. The documentation starts with __Publishing Your Package__ and then the next topic is __Publishing METADATA manually__. It's not until later that there are instructions on __Tagging Package Versions__.

Maybe combing tagging with the Publishing section? Call it __Tagging and Publishing Your Package__

**Comment by tkelman** [comment]
+1

**Comment by tkelman** [comment]
Wherever this goes, it should also include a reminder/clarification about the meaning of the `0.3-` version number syntax, to discourage using it where it isn't appropriate.

**Comment by milktrader** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/2717

**Comment by milktrader** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/2723

**Comment by milktrader** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/2719

**Comment by milktrader** [comment]
Ok, I'll start on this.

**Comment by milktrader** [comment]
I think the salient point is that there is no point in publishing a package that hasn't been tagged.

**Comment by tkelman** [comment]
Should we close this given the awesome job you did in https://github.com/JuliaLang/julia/issues/11716?

**Comment by milktrader** [comment]
Yes, thanks!

**Comment by dpsanders** [comment]
Can we maybe change Pkg.publish() to reject publishing a package that isn't tagged and give a message?

**Comment by milktrader** [comment]
+1

**Comment by jiahao** [comment]
See #2064

Looks like opinion is in favor of merging it. Will update and merge.
