### ISSUE TITLE
Renaming `hwloc` to `Hwloc`

### ISSUE THREAD

**Issue by eschnett** [JuliaLang/METADATA.jl#3381]
I tried to rename the registered package `hwloc` to `Hwloc` to follow the community standards wrt. capitalization. So far, I renamed the Github repository and updated the urls; however, I don't know whether there is an internal place in `METADATA` where the lower-case version still appears. For example, the source code listing on Github still lists the lower-case variant. In hindsight, I should have inquired with you before doing so.

I hope I didn't break things too badly. Could you check whether things are fine, and let me know if I need to do something?

**Comment by tbreloff** [comment]
If you're going to go through the trouble of renaming, how about really
keeping with community standards with something like "HardwareLocality".

**Comment by tkelman** [comment]
This is binding an upstream library that's called hwloc, so I think Hwloc.jl is the right name for the package. Renaming packages is fiddly and troublesome, and this situation where it's case-only also has some annoying interactions with case-insensitive file systems. Github will auto-redirect if you changed the repository name so it should still be clonable via the lower-case old URL. I'm not sure whether or not anything is broken currently, but let's leave things as they are and collect a little bit more information.

**Comment by tkelman** [comment]
cc @IainNZ interesting PackageEvaluator on my most recent runs is giving `ERROR: unknown package hwloc` so it might not be addable on Linux in the current state. Let's try some renamings in local copies of METADATA and see if that helps. Did anything depend on this package?

**Comment by IainNZ** [comment]
@tkelman there are no tagged versions, so thats why PkgEval can't add it.

**Comment by tkelman** [comment]
Aha, I should have checked that. Let's just capitalize the folder here and update https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/hwloc/url then. I'm fine with possible breakage if it was only ever installable via `Pkg.clone`.

**Comment by eschnett** [comment]
@IainNZ I tried to tag version 0.1.0 earlier today; I didn't receive any errors.

**Comment by tkelman** [comment]
closed by #3401
