### ISSUE TITLE
Clarification/Documentation of policy for deprecating packages

### ISSUE THREAD

**Issue by kmsquire** [JuliaLang/METADATA.jl#347]
There are two two issues I would like to see clarified:

~~1) sha1 bumping should (almost) always accompany a new version (with exception of version 0.0.0).  (Does current policy allow bumping of any x.x.0 version?  Should this only be in effect for released versions of Julia?)~~

~~Rationale: no matter how careful one is, some new version will break on someone's system, and it's important to allow the user to revert to a previous version.  Without bumping the version, this is hard for the naive user.~~

2) Old versions of packages should (almost) never removed from METADATA.jl

Rationale: Removing a package version from METADATA.jl causes problems when 1) a package depends on a removed version of a package, or 2) a user wants to replicate some results produced with a particular version of a package, and that version is removed.

---

My impression is that these are policy, or at least should be, but I don't think they're documented, and both have been violated

Any suggestions/objections/refinements?  Should I file an additional issue for Pkg2 to support updating packages?

**Comment by jiahao** [comment]
I think what happened in #2346 is an extreme example where the right thing to do really is to scrub the entirre record from METADATA.

**Comment by hayd** [comment]
Is METADATA supporting 0.2 (or -) users indefinitely??

Perhaps similar to @IainNZ's great work on the pkg tests, there could be a package health heuristic for automatically putting "unhealthy" packages up for deprecation consideration. E.g.

- recent release
- tests pass (supports most recent julia release)
- has documentation
- recent git activity
- latest git issue(s) responded to

If these were all/mostly bad then first ping the maintainers to fix things, and if the health does not improve then flag for the community to consider removal.

*Some packages may fail some of the above but needn't be removed, e.g. they are important or failing X is no big deal, or it may be they can be moved (e.g. to a julia org).*

**Comment by wildart** [comment]
As issue [PkgDev/#21](https://github.com/JuliaLang/PkgDev.jl/issues/21) suggested, there should be some functionality to deregister/unmaintain/unlist registered packages.

I propose to add `unlist` empty file to the root of a package folder which would indicate that the particular package should not be installed/used. If developer will decide to resume development this file will be deleted.

All necessary functionality will be provided by `PkgDev`.

**Comment by IainNZ** [comment]
Whats wrong with the current approach?

**Comment by wildart** [comment]
Zeroing version disables only a particular version of package on which this operation was performed. If package has multiple versions, then other versions can be accessed, unless you set requirements to zero in every version.

**Comment by IainNZ** [comment]
The current approach is to set a Julia version cap for every version

**Comment by wildart** [comment]
Ok, I though only last version get updated. Anyway, what if package is needed to be restored, then the version requirement  information is lost. Well, not completely, it's in METADATA commits, and a new version of the package must be issued anyway. I am just weighing arguments. Current, solution was developed because, we needed to "deregister" packages without changes in work of the package manager. By adding additional information to the package registration we could warn user about installing an old & unmaintained package (e.g. add `unmaintan` file) or completely deregister (e.g. add `unlist` file) a package.

**Comment by tkelman** [comment]
Deregistering is potentially dangerous if anything depends on the package in question yet. You're aware of last weeks' npm left-pad fiasco, right?

The only thing needed to restore a deprecated package is tag a new version that supports up-to-date julia versions. `PkgDev.deprecate` would make sense to formalize and automate the existing pattern of adding an upper bound to all past tags.

**Comment by wildart** [comment]
I would not worry about deprecation so match, cause we have screening process when merge any PR.

As for zeroing all versions in package, it looks as a drastic measure. Adding additional info to package description fills less invasive then changing content of multiple files. Plus, we can get different and more verbose messages on various pieces of information, rather then saying "not available".

**Comment by tkelman** [comment]
Except that "package description" does not formally exist in current package manager functionality. It could if https://github.com/JuliaLang/julia/issues/11955 gets implemented (which would also allow more specific error messages as you suggest), but I'd call that more invasive than bounding multiple tags in metadata. Nothing is zeroed, just add an upper julia version bound.

**Comment by wildart** [comment]
Adding upper bound does not guaranty that package would not be used, or would not inform user that the package is unmaintained.

**Comment by tkelman** [comment]
It will no longer be possible to install with `Pkg.add`. That's good enough for me. Of course a note in the readme would be ideal, but when a package is abandoned there's often not much we can do about it.

**Comment by wildart** [comment]
I see it as a problem, what if a package is functional, but a developer decides that it will not going to maintain it. Why would this package be prohibited from installation? Wouldn't it be better to mark a package as unmaintained and to inform user, which installs it, about that?

**Comment by tkelman** [comment]
That could be accomplished with a `warn` on `using`, couldn't it? There's no mechanism in Pkg for that kind of thing right now, and as far as things we could use 11955 to accomplish this seems like it would be low on the list.

**Comment by Nosferican** [comment]
There are more packages that started including parsable metadata such as [`repo status`](http://www.repostatus.org/). Could part of that information be included in the metadata and displayed during installation or changes during updating?

For obsolete packages, a sensible option would be to allow it as long as it passes its test for the Julia version the user is using when installing it (inferred upper limit). The other case would be a depreciated package which should be replaced. Maybe releasing a version for updating the metadata with a depreciated use `X` package instead tag.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
