### ISSUE TITLE
Removing package says that it's unregistered

### ISSUE THREAD

**Issue by dpsanders** [JuliaLang/METADATA.jl#3595]
```
julia> Pkg.rm("LaTeXStrings") 
INFO: Removing LaTeXStrings (unregistered)
```

"unregistered" does not seem to be correct here, since the package is registered in METADATA.
I presume the idea is to point out that it's not listed explicitly in my `REQUIRE` file?

**Comment by jiahao** [comment]
This looks related to JuliaLang/julia#7757

**Comment by IainNZ** [comment]
This should probably be on JuliaLang, I'm not sure it'll get fixed here. I've seen this too.
@dpsanders, maybe open a new issue these if @jiahao 's link isn't right
