### ISSUE TITLE
Mayday.jl package name feedback

### ISSUE THREAD

**Issue by rdeits** [JuliaLang/METADATA.jl#4921]
Hi all,

I've recently put together a package for performing optimization over sums-of-squares polynomials, built on top of JuMP. These polynomials are useful in, for example, control theory where we use them to prove that a particular dynamical system will be stable or will remain within some set of states. More concretely, we might use them to prove that an aircraft will remain within some known deviation from its desired trajectory. Here's the package: https://github.com/rdeits/Mayday.jl

I picked the name Mayday.jl as a pun on the common abbreviation SoS for sums-of-squares, and because [SumOfSquaresOptimization](https://github.com/willperry/SumOfSquaresOptimization.jl) and [Polyopt](https://github.com/MOSEK/Polyopt.jl) are already packages in this space.

However, before submitting Mayday.jl package to METADATA, I noticed that there is another more well-established software tool with the same name: http://it.inf.uni-tuebingen.de/?page_id=248

I'd like to get some feedback from the community on this decision before I submit the package. Currently, I think my options are:

1. stick with Mayday.jl
2. rename to something more specific, like MaydayOpt or MaydayOptimization
3. choose something else entirely

I'd appreciate any advice you can give. 

-Robin

**Comment by StefanKarpinski** [comment]
The name seems acceptable to me – it strikes me as a classic "whimsical" package name. I don't think anyone would likely confuse it with some other meaning of "mayday". There doesn't seem to be an obvious name for this, so using a whimsical name seems reasonable.

**Comment by joehuchette** [comment]
:+1: to Mayday. The name is nice (and meaningful), the odds of a name conflict with the existing software is fairly speculative, and there isn't a satisfying alternative name (that I can think of).

**Comment by rdeits** [comment]
Okay, that's great! I'm glad you like the name. I'm sufficiently convinced that I'll go ahead and open a pull request.
