### ISSUE TITLE
Is it possible to rename a package?

### ISSUE THREAD

**Issue by paulhendricks** [JuliaLang/METADATA.jl#4951]
For example, I just released MachineLearningMetrics.jl to METADATA.jl. I talked with some people at JuliaML and we'd like to bring that package into their organization, but instead under the MLMetrics.jl. Is it possible to rename the package?

**Comment by paulhendricks** [comment]
MachineLearningMetrics.jl is extremely new, very niche, and I would imagine current adoption is next to none. I understand there was a problem changing Stats.jl to StatsBase.jl (I believe) in 0.2.0, but MachineLearningMetrics.jl is no where near as critical to Julia nor is it a dependency. Perhaps these are different circumstances?

**Comment by nalimilan** [comment]
I guess you could simply register the new package, and then deprecate the old one (by making it depend on Julia version 0.0).

**Comment by paulhendricks** [comment]
@nalimilan Sounds good. I will:
* Deprecate MachineLearningMetrics.jl and keep it under paulhendricks/MachineLearningMetrics.jl.
* Register a new package MLMetrics.jl with METADATA.jl and point it to JuliaML/MLMetrics.jl.

**Comment by tkelman** [comment]
The deprecation process is actually to add a Julia upper bound to all past tags of the package. Julia version 0.0 is meaningless, you'd only add that as a lower bound if you didn't already have one. But your package is recent enough that it does.

**Comment by paulhendricks** [comment]
@tkelman I think I see but just so I'm on the same page.

Currently, the `REQUIRE` file reads:

```
julia 0.4
```

To deprecate MachineLearningMetrics.jl, all I have to do is edit the `REQUIRE` file in all past tags to read:
```
julia 999.999
```

Am I correct in thinking this ensures there is an upper bound and uninstallable, and is thus "deprecated"?

**Comment by tkelman** [comment]
No, set `julia 0.4 0.5` or similar, where the upper bound has not yet been released. Otherwise you're breaking anyone who already has the package installed. Good to add a last tag that warns users about the deprecation, too.

**Comment by giordano** [comment]
> Good to add a last tag that warns users about the deprecation, too.

How?

**Comment by tkelman** [comment]
I think a warning in the readme and at package load time would be good enough.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
