### ISSUE TITLE
I don't understand how requires is built.

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/METADATA.jl#5108]
From https://github.com/sbromberger/METADATA.jl/commit/1dd4eb35d79b14863d6bd5ca590e81c65500ab9f

It shows that Combinatorics is required. However, it is not in LightGraphs `REQUIRE`. Is this a recursive list of dependencies?

**Comment by tkelman** [comment]
It was in REQUIRE at that tagged commit. That commit is just 2 months old. Be sure you're on lastest master before you do Pkg.tag.

**Comment by sbromberger** [comment]
I'm not sure I understand. That tagged commit, among other things, removed Combinatorics. I did a `Pkg.update()`, `Pkg.tag("LightGraphs)`, and `Pkg.publish()` in that order to get that file. What am I doing wrong?

**Comment by tkelman** [comment]
You're repeatedly re-tagging the same commit. See how https://github.com/sbromberger/METADATA.jl/blob/1dd4eb35d79b14863d6bd5ca590e81c65500ab9f/LightGraphs/versions/0.5.4/sha1 and https://github.com/sbromberger/METADATA.jl/blob/1dd4eb35d79b14863d6bd5ca590e81c65500ab9f/LightGraphs/versions/0.5.3/sha1 are exactly the same? You should be on latest master before you make a new tag, you're missing `Pkg.checkout("LightGraphs")` before you do `Pkg.update()`

**Comment by sbromberger** [comment]
I'm pretty sure I'm on the latest master - I did a `git pull` after merging the PR that removed Combinatorics. Then, `Pkg.update()`,...
