### ISSUE TITLE
"Sorry, we had to truncate this directory to 1,000 files. 6 entries were omitted from the list."

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/METADATA.jl#5113]
This shows up at top of the file listing.

**Comment by Keno** [comment]
It's only the display of files, they are still there if you clone it.

**Comment by tkelman** [comment]
It's a github thing. We'd need to introduce sharding (which we should probably do anyway) to fix it.

**Comment by ararslan** [comment]
How breaking would it be to introduce a structure like https://github.com/KristofferC/METADATA.jl?

**Comment by mayuresh-srivastava** [comment]
is there any way to see the omitted files? Files are there but not showing due to truncation. Even file finder not showing, omitted files.

**Comment by aviks** [comment]
@mayureshmayur you can clone the repo to a local disk and browser it there. But this is just a store of metadata, not meant for browsing. Further, this repo is now deprecated, look to the General registry for the current packages. 

Closing this, since there is nothing to do here.

**Comment by SREEND01** [comment]
Sorry, we had to truncate this directory to 1,000 files. 481 entries were omitted from the list - how to see all the files in GitHub?

**Comment by timholy** [comment]
This repo isn't used anymore (it says so on the home page in multiple places). Use a 1.x version of Julia and [the `General` registry](https://github.com/JuliaRegistries/General).
