### ISSUE TITLE
Try using a pull request template?

### ISSUE THREAD

**Issue by tkelman** [JuliaLang/METADATA.jl#5307]
Ref https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ - this would likely be easier than writing an automatic metadata review bot, but wouldn't actually verify anything. It would just serve as a reminder when registering / tagging packages of the checklist of recommended steps (most of which Pkg[Dev].tag and Pkg[Dev].publish should be doing for you, if they're working correctly). These are things I spend a few seconds checking manually when I review/merge a metadata PR. I could propose a list of items and wording to solicit feedback if people think it's a good idea.

**Comment by quinnj** [comment]
+1j

**Comment by gragusa** [comment]
👍

**Comment by ararslan** [comment]
I think this will become less necessary as more people adopt attobot. I'm not sure how attobot would do with the PR body prefilled. Though it may still be useful to have for the folks who don't use attobot.

**Comment by tkelman** [comment]
would be useful if there were a way of propagating a template through attobot somehow

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
