### ISSUE TITLE
Notifications for new registered packages

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/METADATA.jl#5997]
Is there any way to receive a notification only when a new package is registered? I tried to use GitHub's "Watch" functionality to follow `METADATA.jl`, but it is too noisy as expected :)

It would be great to have a RSS feed or other alternative where all new registered packages are reported.

**Comment by tkelman** [comment]
scrape http://pkg.julialang.org/pulse.html for "new" ?

**Comment by juliohm** [comment]
Hi @tkelman, is there any way watch the new packages in the website with a RSS feed?

**Comment by tkelman** [comment]
not that i know of. if someone wants to build such a thing, go for it.

**Comment by juliohm** [comment]
I don't have the experience for doing it properly, if anyone knows how to
do it, that would be valuable for the community in my opinion!

-Júlio

**Comment by juliohm** [comment]
Feel free to close the issue. :)

-Júlio
