### ISSUE TITLE
0.4 -> 0.5, LightGraphs, and tags.

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/METADATA.jl#6155]
Hi (especially @tkelman):

I need some guidance with respect to how to correctly version LightGraphs. Right now the latest version (0.6.1) is upper-bounded with `0.5-`, which is accurate since it doesn't work on 0.5 due to the removal of `issym`. We have a branch of LightGraphs called `bleeding-edge` that passes all tests on 0.5 (but is not compatible with 0.4 for the same reason).

LG's policy is to support stable versions of Julia and prereleases on a best-effort basis

The current situation is causing some problems (see https://github.com/JuliaLang/METADATA.jl/pull/6151) for packages that depend on LG. I'm wondering whether the following strategy makes sense:

1) tag a new version of LG (0.7.0) with a lower bound for Julia of `0.5-` and an upper bound of `0.6-`.
2) retroactively modify the bounds on all previous versions (especially those that have no upper bounds).
3) cherry pick as much as possible during this instability.

This would allow Julia 0.4 users to keep on 0.6.1, while forcing 0.5 users to use the 0.7.x version. Once 0.5 is released, we stop development of the 0.6 tree and move exclusively to 0.7.

Comments / feedback please?

**Comment by tkelman** [comment]
Unless you apply upper bounds on every single past tag, the only thing they accomplish is resulting in people not using the latest tag when they're on a version of Julia at or above your upper bound. So I don't think you should be applying upper bounds at all at this point - let the latest version of the package be installable, even if it doesn't work.

If you can tag a version that does work on 0.5, great. Do so as soon as you can. If that version does not work on 0.4, then all you have to do is set a minimum Julia version of `0.5-` for the 0.5-compatible tags, then everything you want to happen will happen. Users on Julia 0.4 will only get the previous 0.4-compatible tags, users on Julia 0.5 will get the newest possible tags that are allowed.

**Comment by sbromberger** [comment]
Thanks for the advice. I think we'll go with that for now, but I do want to apply upper bounds on every single past tag at some point so we don't have this problem when 0.6 rolls around.

**Comment by tkelman** [comment]
> Can you tag a version from another branch?

Yes, you can.

**Comment by tkelman** [comment]
> I do want to apply upper bounds on every single past tag at some point so we don't have this problem when 0.6 rolls around.

I don't think this would accomplish anything useful. Nightly is already 0.6-dev. If you apply an `0.6-` upper bound to every single tag of LightGraphs, that makes LightGraphs and hence every package that depends on it impossible to install on nightly.

**Comment by sbromberger** [comment]
Gotcha. OK. So, here's what I think is the plan:

1) Tag 0.7.0 from branch `0.5-compat` with a lower bound of Julia `0.5-`
2) Keep LG master working on 0.4
3) when Julia 0.5 comes out, merge `0.5-compat` into master and tag 0.7.1

Does that sound right? (Thanks for all the help, btw.)

**Comment by tkelman** [comment]
Yep that sounds like a good plan.

**Comment by sbromberger** [comment]
Thanks again. I think I've got it.
