### ISSUE TITLE
Document publishing checklist and troubleshooting

### ISSUE THREAD

**Issue by joaquimg** [JuliaLang/METADATA.jl#6857]
The julia manual has a good documentation around publishing here https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/README.md and here http://docs.julialang.org/en/release-0.5/manual/packages/#guidelines-for-naming-a-package

But also @tkelman prepared a pretty nice check list that should be added somewhere: see https://github.com/JuliaLang/METADATA.jl/issues/6761#issuecomment-253893450 

More over I could not find anywhere how to proceed if there is some problem in the pull request, do we need to make a new tag and delete the old one? How should we proceed?

Maybe this second part should be in [PkgDev.jl](https://github.com/JuliaLang/PkgDev.jl):
But what should we do if we tagged the wrong commit by accident? 

Or if we tagged the correct commit but with an undesired version?

Or if we PkgDev.publish (without doing the PR) the tag of the wrong commit?

I thing all those and maybe more, could be very useful for non-experts on git, that have packages to maintain.

**Comment by joaquimg** [comment]
Using [AttoBot](https://github.com/attobot/attobot) makes it much better to release and update packages.

It solves most of these questions and prevents many errors and problems arising from doing everything manually.

**Comment by DilumAluthge** [comment]
METADATA.jl is no longer maintained, so I am closing this issue.

If this issue is still relevant, please re-open a new issue on the Julia General registry: https://github.com/JuliaRegistries/General
