### ISSUE TITLE
disable squash merge?

### ISSUE THREAD

**Issue by simonbyrne** [JuliaLang/METADATA.jl#7326]
Given https://github.com/JuliaLang/julia/pull/19624, should we disable squash merge until the fix is in the release version?

**Comment by tkelman** [comment]
Or fix PkgDev to create a branch when tagging, which we've needed to do for some time.

**Comment by tkelman** [comment]
And for attobot pr's the libgit2 issue won't matter. I personally prefer the history being a bit more compact with less merge commit noise, but if it's causing people local hassle then I guess it should be avoided for old-style tag pr's until libgit2 bindings or pkgdev get fixed.

**Comment by tkelman** [comment]
fixed in 0.5.1
