### ISSUE TITLE
Process for tagging LightGraphs 1.0.0

### ISSUE THREAD

**Issue by sbromberger** [JuliaLang/METADATA.jl#8454]
Hi @tkelman -

We'd like to propose the following rollout process for your review and concurrence:

1) Tag a final version of LightGraphs that is compatible with 0.5
2) Tag LightGraphs v1.0.0, dropping 0.5 support
3) Soon thereafter, tag LightGraphs 1.1.0 with some persistence deprecations.

I know it's a bit unorthodox to tag a release that precedes the released Julia version, but this will let us move directly to the major (and labor-intensive) changes we need to make to satisfy some heavy LG users.

Thoughts?

**Comment by tkelman** [comment]
Wrong repo for this issue.

**Comment by sbromberger** [comment]
Sorry 'bout that. Where should it have gone?

**Comment by tkelman** [comment]
where you already had it at https://github.com/JuliaGraphs/LightGraphs.jl/issues/561 - you can tag me if you really think I need to know in advance, but this all seems normal
