### ISSUE TITLE
Broken packages

### ISSUE THREAD

**Issue by juliohm** [JuliaLang/METADATA.jl#8661]
Can I submit a PR to remove all broken packages from METADATA?

https://juliohm.github.io/science/DAG-of-Julia-packages/

**Comment by tkelman** [comment]
No. METADATA is append only, except for requirement bounds.

**Comment by tkelman** [comment]
You can propose deprecating obsolete packages that don't load on recent julia by adding julia version upper bounds to all their tagged versions.

**Comment by juliohm** [comment]
Hi @tkelman, but those broken packages don't have any tag, is that right? For instance, `AuditoryFilters`, doesn't have a `versions` folder.

**Comment by tkelman** [comment]
Right, so you can't Pkg.add them, but you can Pkg.clone them with just a name, not a full url. It's a separate state in Pkg2 that we don't allow any more for new packages, and Pkg3 probably won't have, but it doesn't do any harm to leave them here.

**Comment by juliohm** [comment]
Understand, I thought a tag was required for registering a package in METADATA from the start, I personally don't see benefit in cloning with a name instead of cloning with a full URL. I think that deleting them wouldn't harm either. At least would keep METADATA "more consistent".

**Comment by tkelman** [comment]
It is required now for new packages, but that's a policy we haven't always enforced.
