### ISSUE TITLE
Relax requirement for `.jl` suffix in git repository name

### ISSUE THREAD

**Issue by SylvainCorlay** [JuliaLang/METADATA.jl#9480]
At the moment, CI checks that the repository URL has a `.jl` suffix in its name.

This does not seem to be a requirement for `Pkg`, which can do `Pkg.clone(URL, name)`, and is only a convention. Also, it does not seem to be documented.

Would it be possible to relax this requirement and allow URLs to be any valid git repository?

For example, for the xtensor package, I have the folling repositories: `xtensor`, `xtensor-python`, `xtensor-blas`, `xtensor-julia`, and I had to rename the latter in `Xtensor.jl`.

**Comment by tkelman** [comment]
You wouldn't be able to name a package `xtensor-julia` since a module can't have an operator in its name. The `.jl` isn't strictly required, but I think it's a useful convention as long as the package manager requires a one-to-one correspondence between git repository and package.

**Comment by SylvainCorlay** [comment]
The julia package name would still be `Xtensor.jl`.
This is only foe the url. At the moment we can already do

```
Pkg.clone (".../xtensor-julia.git", "Xtensor.jl")
```

**Comment by tkelman** [comment]
Would be pretty confusing for the package name and its url not to match.

**Comment by SylvainCorlay** [comment]
In any case if some julia package becomes e.g. a debian package, they will apply the debian package naming conventions, which is to add a prefix with the language name and a dash, have a dev suffix for header packages and a doc suffix for the documentation etc...

A git repository url is orthogonal to all of that. The author can decide to match the debian package name or the thing that is imported in julia or anything else...

**Comment by SylvainCorlay** [comment]
@tkelman would you guys not consider removing this constraint?

Package name and repository URL are logically two different things. This is only a CI check in the `METADATA.jl` repository, not something hardcoded in `Pkg`.

**Comment by Nosferican** [comment]
It is already possible, but not recommended. I think this issue can be closed.
